### ISSUE TITLE
failure to install

### ISSUE THREAD

**Issue by jmaggiore** [dynverse/dyngen#23]
>devtools::install_github("dynverse/dyngen", dependencies = TRUE)
Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo dynverse/dyngen@HEAD
✓  checking for file ‘/private/var/folders/8z/lxzvvn0n5972z0y7kr0t120m0000gn/T/RtmpPM91Tx/remotesa89d4cb9ce40/dynverse-dyngen-0967ed8/DESCRIPTION’ ...
─  preparing ‘dyngen’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘dyngen/vignettes/getting_started_files/figure-gfm’
   Removed empty directory ‘dyngen/vignettes/getting_started_files’
   Removed empty directory ‘dyngen/vignettes/showcase_backbones_files/figure-gfm’
   Removed empty directory ‘dyngen/vignettes/showcase_backbones_files’
─  building ‘dyngen_0.4.0.tar.gz’
   
* installing *source* package ‘dyngen’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/GillespieSSA2/libs/GillespieSSA2.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/GillespieSSA2/libs/GillespieSSA2.so, 6): Symbol not found: _EXTPTR_PTR
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/GillespieSSA2/libs/GillespieSSA2.so
  Expected in: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib
 in /Library/Frameworks/R.framework/Versions/4.0/Resources/library/GillespieSSA2/libs/GillespieSSA2.so
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘dyngen’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/dyngen’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/dyngen’
Error: Failed to install 'dyngen' from GitHub:
  (converted from warning) installation of package ‘/var/folders/8z/lxzvvn0n5972z0y7kr0t120m0000gn/T//RtmpPM91Tx/filea89d3a93f31a/dyngen_0.4.0.tar.gz’ had non-zero exit status
>

**Comment by rcannood** [comment]
Hello @jmaggiore,

This seems to be an issue with R 4.0.0 ([source](https://stackoverflow.com/a/63088455)). If you are running R 4.0.0, could you try updating to R 4.0.2 and then reinstalling GillespieSSA2/dyngen?

Please let me know if this has solved your issue.

Kind regards,
Robrecht

**Comment by jmaggiore** [comment]
Worked!!
