### ISSUE TITLE
simulation_type_knockdown no multiplier effect

### ISSUE THREAD

**Issue by HectorRDB** [dynverse/dyngen#25]
Hi,
Thanks a lot for the tools, they are great. 
I have been following the [knockout vignette](https://github.com/dynverse/dyngen/blob/devel/vignettes/advanced_simulating_knockouts.md) from the devel branch and I wanted to change the `multiplier` parameter of the `simulation_type_knockdown` function. However, this seems to have no effect on the output of the function. 
When I use the `plot_gold_mappings(model_ko, do_facet = FALSE)` I still see that all cells only go through one lineage (and I also see the warning) when setting `multiplier` to `.5` or `.2.
Thanks a lot for the help,
Best

**Comment by HectorRDB** [comment]
Sorry, it was actually a typo on my part, I was updating the wrong variable.

**Comment by rcannood** [comment]
Hello Hector! 

Happy to hear the problem was solved relatively easily :) 

Kind regards,
Robrecht
