### ISSUE TITLE
dyngen removed from CRAN

### ISSUE THREAD

**Issue by scottgigante-immunai** [dynverse/dyngen#46]
From [CRAN](https://cran.r-project.org/web/packages/dyngen/index.html):

> Package ‘dyngen’ was removed from the CRAN repository.
> 
> Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/dyngen).
> 
> Archived on 2022-09-04 as issues were not corrected in time.
> 
> A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2022/2022-09-04_check_results_dyngen.html).
> 
> Please use the canonical form https://cran.r-project.org/package=dyngen to link to this page.

**Comment by rcannood** [comment]
Wat. Ugh. I'd fixed the problems they contacted me about, but a new problem
popped up in a different place.

I'll look into it, thanks for letting me know!

**Comment by rcannood** [comment]
In the meantime, dyngen is back on CRAN. Thanks for letting me know it was removed!
