### ISSUE TITLE
Can't open anndata object 

### ISSUE THREAD

**Issue by sarajimenez** [dynverse/dyngen#49]
Hi, 
Thanks for this amazing tool! 
I went through the tutorial to generate a gold standard data set I could use to compare the performance of some tools for downstream analysis. 
In the end, I've saved the output as an anndata object because my downstream analysis pipeline is python based. However, when I try to open the generated anndata file, I get the following error: 

`AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.`

Do you have any idea of how I can overcome this? any input would be highly appreciate it :) 

Best,
Sara

**Comment by rcannood** [comment]
Hi Sara,

Please ensure you have anndata>=0.8 installed. Can you confirm this solves your issue ?

Robrecht

**Comment by sarajimenez** [comment]
Hi Robrecht, 

upgrading anndata to 0.8 solved the problem! thanks a lot :) 

I was also wondering, could you please comment on which argument of the anndata object refers to the GRN? 
I initially thought it was adata.uns['traj_milestone_network'] but, I think the information there is not enough to reconstruct the interactions between TFs and targets. 

Thank you! 
Sara

**Comment by rcannood** [comment]
I'm closing this issue, as the original issue has been resolved.
