### ISSUE TITLE
Where is the GRN stored?

### ISSUE THREAD

**Issue by rcannood** [dynverse/dyngen#52]
I was also wondering, could you please comment on which argument of the anndata object refers to the GRN? 
I initially thought it was adata.uns['traj_milestone_network'] but, I think the information there is not enough to reconstruct the interactions between TFs and targets. 

_Originally posted by @sarajimenez in https://github.com/dynverse/dyngen/issues/49#issuecomment-1294049046_

**Comment by rcannood** [comment]
Hi Sara,

The GRN is only stored in the anndata when the cellwise GRNs are computed as well:

```r
library(tidyverse)
library(dyngen)

set.seed(1)

backbone <- backbone_bifurcating()
config <- 
  initialise_model(
    backbone = backbone,
    num_tfs = nrow(backbone$module_info),
    num_targets = 500,
    num_hks = 500,
    simulation_params = simulation_default(compute_cellwise_grn = TRUE), # <- this
    verbose = FALSE,
    num_cores = 30
  )

out <- generate_dataset(
  config,
  format = "anndata",
  make_plots = TRUE
)
```

The dataset now contains `.obsm['regulatory_network_sc']` and `.uns['regulatory_network']`:

```{r}
out$dataset
```

    AnnData object with n_obs × n_vars = 1000 × 1035
        obs: 'step_ix', 'simulation_i', 'sim_time'
        var: 'module_id', 'basal', 'burn', 'independence', 'color', 'is_tf', 'is_hk', 'transcription_rate', 'splicing_rate', 'translation_rate', 'mrna_halflife', 'protein_halflife', 'mrna_decay_rate', 'protein_decay_rate', 'max_premrna', 'max_mrna', 'max_protein', 'mol_premrna', 'mol_mrna', 'mol_protein'
        uns: 'traj_milestone_network', 'traj_progressions', 'traj_dimred_segments', 'regulatory_network', 'regulatory_network_regulators', 'regulatory_network_targets'
        obsm: 'dimred', 'regulatory_network_sc'
        layers: 'counts_spliced', 'counts_unspliced', 'counts_protein', 'logcounts'

```r
out$dataset$uns$regulatory_network
```

    # A tibble: 1,188 × 4
       regulator target    strength effect
       <chr>     <chr>        <dbl>  <int>
     1 Burn1_TF1 Burn2_TF1        1      1
     2 Burn2_TF1 Burn3_TF1        1      1
     3 Burn3_TF1 Burn4_TF1        1      1
     4 Burn4_TF1 A1_TF1           1      1
     5 A1_TF1    A2_TF1           1      1
     6 A2_TF1    A3_TF1           1      1
     7 A3_TF1    A4_TF1           1      1
     8 A4_TF1    A5_TF1           1      1
     9 A5_TF1    A6_TF1           1      1
    10 A6_TF1    B1_TF1           1      1
    # … with 1,178 more rows
    # ℹ Use `print(n = ...)` to see more rows

The regulatory_network_sc is a matrix with one row per cell and one column per interaction.

```r
out$dataset$obsm[["regulatory_network_sc"]]
```

    1000 x 1188 sparse Matrix of class "dgCMatrix

If you can't or don't want to compute the single-cell GRN, for some reason, you can always extract it from the model yourself:

```r
grn <- out$model$feature_network %>% 
  select(regulator = from, target = to, strength, effect)
grn
```

    # A tibble: 1,188 × 4
       regulator target    strength effect
       <chr>     <chr>        <dbl>  <int>
     1 Burn1_TF1 Burn2_TF1        1      1
     2 Burn2_TF1 Burn3_TF1        1      1
     3 Burn3_TF1 Burn4_TF1        1      1
     4 Burn4_TF1 A1_TF1           1      1
     5 A1_TF1    A2_TF1           1      1
     6 A2_TF1    A3_TF1           1      1
     7 A3_TF1    A4_TF1           1      1
     8 A4_TF1    A5_TF1           1      1
     9 A5_TF1    A6_TF1           1      1
    10 A6_TF1    B1_TF1           1      1

Is this what you were looking for?

**Comment by sarajimenez** [comment]
Hi Robrecht, 

Thank you for your detailed response! It was very useful. It's indeed what I'm looking for. 

I'll close this.
