### ISSUE TITLE
Query regarding documentation

### ISSUE THREAD

**Issue by atuldeshpande** [dynverse/dyngen#7]
We are planning to use dyngen as a source for simulated single-cell dataset to evaluate various network inference methods. Where will I be able to find additional documentation related to the package with respect to extracting the true network and cell timestamps?

**Comment by rcannood** [comment]
Hello Atul!

I apologise for the state of dyngen ─ I'm in the midst doing a complete rewrite of dyngen. You can see this in branch [rework_new](https://github.com/dynverse/dyngen/tree/rework_new/R). I can't really recommend running it until I've merged everything to master, since you would need to install all the development packages of dynverse. However, I can already give you [some example output files](https://cloud.irc.ugent.be/public/index.php/s/bspNnmpTYdigfZP).

You can write the parts of the model that you need as follows:
```R
setwd("bifurcating_1/")

library(tidyverse)
model <- read_rds("out_model.rds")
names(model) # observe objects in model
names(model$simulations)
model$feature_network

write_tsv(model$feature_network, "feature_network.tsv")

names(model$experiment)
model$experiment$cell_info
model$experiment$feature_info

counts <- model$experiment$counts %>% as.matrix() %>% as.data.frame()
write_tsv(counts, "counts.tsv")
write_tsv(model$experiment$cell_info, "cell_info.tsv")

feature_info <- model$experiment$feature_info %>% select(-as)
write_tsv(feature_info, "feature_info.tsv")
```

**Comment by atuldeshpande** [comment]
Thanks. Those objects are exactly what I was looking for. 
Is there an expected date (rough estimate should work) for the merge? 

I had a few more questions:
Is there a way to isolate the cells on the main path of the trajectory from model$experiment? Alternatively, would it be possible to obtain a dataset with a single non-branching trajectory?
I noticed that the dynverse repository at https://zenodo.org/record/1443566 has a number of dyngen generated models, with the data structure and variables being different in those. Would you recommend against using those models? (Those models do not have either the feature_network object or the $net object which was available.)

**Comment by atuldeshpande** [comment]
@rcannood, I was trying to visualize the datasets you shared with me above, but it seems to me that the plotting functions on the master branch are not compatible with the new datasets. Am I understanding this right?

Also, do you have a dataset for a linear trajectory that I could use?

Thanks.

**Comment by rcannood** [comment]
Hey Atul! 

Sorry for the late response. I lost track of your message.

> Is there an expected date (rough estimate should work) for the merge?
Yes. I'm almost done; I expect to be ready with the new version within 5 to 10 days. I'll let @zouter review it quickly as well. 

> Is there a way to isolate the cells on the main path of the trajectory from model$experiment? 
I'm not sure what you mean by this. All of the cells are on the trajectory.

> Alternatively, would it be possible to obtain a dataset with a single non-branching trajectory?
Certainly! These are included :)

> I noticed that the dynverse repository at https://zenodo.org/record/1443566 has a number of dyngen generated models, with the data structure and variables being different in those. Would you recommend against using those models? (Those models do not have either the feature_network object or the $net object which was available.)
I would indeed advise against using these. The original networks that were used to generate these datasets have been removed, and dyngen underwent major improvements since then.

> I was trying to visualize the datasets you shared with me above, but it seems to me that the plotting functions on the master branch are not compatible with the new datasets. Am I understanding this right?
The plotting functions on the master branch of dyngen is indeed not compatible with the new datasets. You can use the plotting functions of the `rework_new` branch. You can also just copy paste the functions from [this file](https://github.com/dynverse/dyngen/blob/rework_new/R/plotting.R) :) 

> Also, do you have a dataset for a linear trajectory that I could use?
Yes, let me try generating one right now :)

**Comment by agitter** [comment]
@rcannood thanks for the updates.  If this is ready in the next 5-10 days that would be great from our perspective.  Having a linear trajectory will also be useful.

**Comment by rcannood** [comment]
Hey @atuldeshpande @agitter,

I merged the new version of dyngen to the @devel branch (`devtools::install_github("dynverse/dyngen@devel")`). I should still write a few vignettes for the new version, but normally you should be able to get started by having a look at the [README](https://github.com/dynverse/dyngen/blob/devel/README.md). Take into account that the genes are split into TFs, targets, and housekeeping genes, and that including a lot of housekeeping genes might result in datasets for which it is very difficult to infer a GRN.

Robrecht

**Comment by atuldeshpande** [comment]
Thanks @rcannood!

I am encountering an error while installing the fastgssa@devel package as part of the dyngen@devel installation.
Downloading GitHub repo dynverse/fastgssa@devel
✔  checking for file ‘/tmp/RtmpLAcFlh/remotes71dadb36dff/dynverse-fastgssa-62b9ab0/DESCRIPTION’ ...
─  preparing ‘fastgssa’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘fastgssa/vignettes/decaying_dimer_files/figure-gfm’
   Removed empty directory ‘fastgssa/vignettes/decaying_dimer_files’
   Removed empty directory ‘fastgssa/vignettes/preparing_a_run_files/figure-gfm’
   Removed empty directory ‘fastgssa/vignettes/preparing_a_run_files’
─  building ‘fastgssa_0.2.0.tar.gz’
   
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘fastgssa’ ...
** using staged installation
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c simulate.cpp -o simulate.o
simulate.cpp: In function ‘Rcpp::List simulate(SEXP, int, SEXP, const NumericVector&, const NumericVector&, const IntegerVector&, const IntegerVector&, const IntegerVector&, double, double, int, double, bool, bool, double)’:
simulate.cpp:180:28: error: ‘isinf’ was not declared in this scope
   if (isinf(census_interval)) {
                            ^
simulate.cpp:180:28: note: suggested alternative:
In file included from /usr/local/lib/R/site-library/Rcpp/include/Rcpp/platform/compiler.h:100:0,
                 from /usr/local/lib/R/site-library/Rcpp/include/Rcpp/r/headers.h:59,
                 from /usr/local/lib/R/site-library/Rcpp/include/RcppCommon.h:29,
                 from /usr/local/lib/R/site-library/Rcpp/include/Rcpp.h:27,
                 from simulate.cpp:1:
/usr/include/c++/5/cmath:621:5: note:   ‘std::isinf’
     isinf(_Tp __x)
     ^
/usr/lib/R/etc/Makeconf:176: recipe for target 'simulate.o' failed
make: *** [simulate.o] Error 1
ERROR: compilation failed for package ‘fastgssa’
* removing ‘/usr/local/lib/R/site-library/fastgssa’
* restoring previous ‘/usr/local/lib/R/site-library/fastgssa’
Error: Failed to install 'dyngen' from GitHub:
  Failed to install 'fastgssa' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpLAcFlh/file71da3ddfdc3f/fastgssa_0.2.0.tar.gz’ had non-zero exit status

**Comment by agitter** [comment]
I ran into the same error as @atuldeshpande when I tried `devtools::install_github("dynverse/dyngen@devel")`.  This was on R 3.6.0 on Windowx 10 x64.

Do we need to install a different version of fastgssa before installing dyngen?

**Comment by rcannood** [comment]
Strange. @atuldeshpande, are you also on Win10?

I've made a small change to fastgssa@devel. Could you try reinstalling it?

```R
devtools::install_github("dynverse/fastgssa@devel")
```

**Comment by agitter** [comment]
Thanks @rcannood, that appears to have fixed the installation error on my system.

**Comment by rcannood** [comment]
@atuldeshpande Does it also work for you?

**Comment by rcannood** [comment]
Woops, clicked the wrong button.

**Comment by atuldeshpande** [comment]
@rcannood
Yes, indeed! Thank you so much for your help!

**Comment by agitter** [comment]
Yes, thank you very much @rcannood.
