### ISSUE TITLE
Error during invoke in dyngen readme example

### ISSUE THREAD

**Issue by dvorael1** [dynverse/dyngen#9]
Hi,
I installed the dyngen package and all other needed packages. I followed instructions in the readme example and I successfully generated a single-cell dataset. 

The issue is that when I try to execute:
model <- invoke(generate_model_from_modulenet, params$model)  
I keep getting this error:

Error in pritt("rg_{cell_id}") : could not find function "pritt"
Error during wrapup: cannot get a slot ("slots") from an object of type "NULL"

Do you have any help for this problem?

Thank you

**Comment by rcannood** [comment]
Hey Eliška,

I merged the new version of dyngen to the @devel branch. I should still write a few vignettes for the new version, but normally you should be able to get started with the new version already. Run `devtools::install_github("dynverse/dyngen@devel")` to install the new version.

Robrecht

**Comment by rcannood** [comment]
I extended the documentation and the README quite a bit. I will be merging the devel branch into master soon (#10), thereby solving this issue. Feel free to open a new issue if you have any further questions regarding dyngen.
